SteamUtils
uint32 GetSecondsSinceAppActive ( )
uint32 GetSecondsSinceComputerActive ( )
EUniverse GetConnectedUniverse ( )
uint32 GetServerRealTime ( )
constchar* GetIPCountry ( )
bool GetImageSize ( int iImage, uint32* pnWidth, uint32* pnHeight )
bool GetImageRGBA ( int iImage, uint8* pubDest, int nDestBufferSize )
bool GetCSERIPPort ( uint32* unIP, uint16* usPort )
uint8 GetCurrentBatteryPower ( )
uint32 GetAppID ( )
void SetOverlayNotificationPosition ( ENotificationPosition eNotificationPosition )
bool IsAPICallCompleted ( SteamAPICall_t hSteamAPICall, bool* pbFailed )
ESteamAPICallFailure GetAPICallFailureReason ( SteamAPICall_t hSteamAPICall )
bool GetAPICallResult ( SteamAPICall_t hSteamAPICall, void* pCallback, int cubCallback, int iCallbackExpected, bool* pbFailed )
void RunFrame ( )
uint32 GetIPCCallCount ( )
void SetWarningMessageHook ( SteamAPIWarningMessageHook_t pFunction )
bool IsOverlayEnabled ( )
bool BOverlayNeedsPresent ( )
SteamAPICall_t CheckFileSignature ( constchar* szFileName )
bool ShowGamepadTextInput ( EGamepadTextInputMode eInputMode, EGamepadTextInputLineMode eLineInputMode, constchar* pchDescription, uint32 unCharMax )
uint32 GetEnteredGamepadTextLength ( )
bool GetEnteredGamepadTextInput ( char* pchText, uint32 cchText )	
constchar* GetSteamUILanguage ( )
